### ISSUE TITLE
Accented or special characters issue

### ISSUE THREAD

**Issue by ScarlitoDoBrazil** [Dolibarr/dolibarr-docker#30]
Hi everyone.

I'm doing a clean install. I tried several options, but none of them fixed the issue.
I tried several character sets and collations for the MariaDB database, but still no luck.
Here is an example of what I get in the DB right after the installation. In the "llx_c_country" for example I get "CÃ´te d'Ivoire" instead of "Côte d'Ivoire". And same goes for any special or accented character as you can see in the following screenshot :

![image](https://github.com/user-attachments/assets/4ca9cbfa-38d1-455e-9475-a96d5afc83ef)

Here is my compose file :

```
networks:
  internal-pod:
    internal: true
  external-pod:
    internal: false

volumes:
  doli-docs:
  doli-custom:
  doli-db:

services:
  dolibarr:
    image: dolibarr/dolibarr:latest
    environment:
      DOLI_DB_HOST: "mariadb"
      DOLI_DB_HOST_PORT: "3306"
      DOLI_DB_USER: "dbuser"
      DOLI_DB_PASSWORD: "dbpassword"
      DOLI_DB_NAME: "dbname"
      DOLI_ADMIN_LOGIN: "admin"
      DOLI_ADMIN_PASSWORD: "adminpassword"
      DOLI_COMPANY_COUNTRYCODE: "FR"
      DOLI_COMPANY_NAME: "MyCompany"
      PHP_INI_DATE_TIMEZONE: 'Europe/Paris'
    ports:
      - 80:80
    volumes:
      - doli-docs:/var/www/documents
      - doli-custom:/var/www/html/custom
    networks:
      - internal-pod
      - external-pod

  mariadb:
    image: mariadb:latest
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_DATABASE: "dbname"
      MYSQL_USER: "dbuser"
      MYSQL_PASSWORD: "dbpassword"
      MYSQL_ROOT_PASSWORD: "dbrootpassword"
    volumes:
      - doli-db:/var/lib/mysql
    networks:
      - internal-pod

  adminer:
    image: adminer
    depends_on:
      - mariadb
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - internal-pod
      - external-pod
```
I tried without the "command" under mariadb, and also with utf8mb4_general_ci, but with no success.
As you can see, all the tables are set to the supposedly good collation :

![image](https://github.com/user-attachments/assets/86e9b6a0-bd5b-4cb0-a506-873f6b9cff5d)

Of course, each time I was starting from scratch (cleaning the volumes, etc.).
I tried on Docker Desktop and also on Container Manager on my Synology NAS. Same result each time.

Any idea ?
